### ISSUE TITLE
Greate Work! And look forward to the codes.

### ISSUE THREAD

**Issue by NeverGiveU** [JinWonjoon/Dr.3D#1]
It is quite interesting and efficient for stylized 3D portraits generation especially the valid geometry!
Im really looking forward to yr codes.

**Comment by JinWonjoon** [comment]
Thanks for your attention.
Codes are released just now!

**Comment by NeverGiveU** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好！您的来信我已收到，我将认真阅读邮件并及时予以您答复！谢谢！
